Add support for export_all
AdRoll/rebar3_hank pull request #210
Opened 2023-05-09 07:09 UTC by kamilwaz

Fixes #209.

2023-05-09 07:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AdRoll/rebar3_hank?pullRequest=210) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AdRoll/rebar3_hank?pullRequest=210) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AdRoll/rebar3_hank?pullRequest=210) it.</sub>

2023-05-09 09:44 UTC, elbrujohalcon requested changes
Minimal change request, just for safety.

2023-05-09 11:05 UTC, elbrujohalcon approved these changes

2023-05-09 18:55 UTC, pbrudnick requested changes
Left a suggestion, but everything looks good to me. Thank you @kamilwaz !

2023-05-09 18:55 UTC, pbrudnick commented on src/rules/unnecessary_function_arguments.erl
> +        {false, Exports, _All} -> Exports
More explicity:
```suggestion
        {true, _Exports, Functions} -> Functions;
        {false, Exports, _Functions} -> Exports
```

2023-05-10 12:40 UTC, pbrudnick approved these changes

2023-05-10 13:57 UTC, elbrujohalcon approved these changes

2023-05-10 13:57 UTC, kamilwaz commented
I missed one commit after rebasing. Now tests are all green.

2023-05-10 13:57 UTC, elbrujohalcon commented
Yeah… The lesson is: you should not rebase ;)

2023-05-10 13:58 UTC, merged